<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * AmendUsageRequestBodyEventsProperties - A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class AmendUsageRequestBodyEventsProperties
{
	public function __construct()
	{
	}
}
