<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class AmendUsageExternalCustomerIdResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\orb\orb\Models\Operations\AmendUsageExternalCustomerId200ApplicationJSON $amendUsageExternalCustomerId200ApplicationJSONObject
     */
	
    public ?AmendUsageExternalCustomerId200ApplicationJSON $amendUsageExternalCustomerId200ApplicationJSONObject = null;
    
    /**
     * Bad Request
     * 
     * @var ?\orb\orb\Models\Operations\AmendUsageExternalCustomerId400ApplicationJSON $amendUsageExternalCustomerId400ApplicationJSONObject
     */
	
    public ?AmendUsageExternalCustomerId400ApplicationJSON $amendUsageExternalCustomerId400ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->amendUsageExternalCustomerId200ApplicationJSONObject = null;
		$this->amendUsageExternalCustomerId400ApplicationJSONObject = null;
	}
}
