<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class AmendUsageRequestBody
{
    /**
     * $events
     * 
     * @var array<\orb\orb\Models\Operations\AmendUsageRequestBodyEvents> $events
     */
	#[\JMS\Serializer\Annotation\SerializedName('events')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Operations\AmendUsageRequestBodyEvents>')]
    public array $events;
    
	public function __construct()
	{
		$this->events = [];
	}
}
