<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class CloseBackfillRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=backfill_id')]
    public string $backfillId;
    
	public function __construct()
	{
		$this->backfillId = "";
	}
}
