<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class CreateInvoiceLineItemRequestBody
{
    /**
     * The total amount in the invoice's currency to add to the line item.
     * 
     * @var string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
    /**
     * An date string to specify the line item's end date in the customer's timezone.
     * 
     * @var \DateTime $endDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('end_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    public \DateTime $endDate;
    
    /**
     * The id of the `Invoice` to add this line item.
     * 
     * @var string $invoiceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('invoice_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $invoiceId;
    
    /**
     * The item name associated with this line item. If an item with the same name exists in Orb, that item will be associated with the line item.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The number of units on the line item
     * 
     * @var float $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $quantity;
    
    /**
     * An date string to specify the line item's start date in the customer's timezone.
     * 
     * @var \DateTime $startDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('start_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    public \DateTime $startDate;
    
	public function __construct()
	{
		$this->amount = "";
		$this->endDate = new \DateTime();
		$this->invoiceId = "";
		$this->name = "";
		$this->quantity = 0;
		$this->startDate = new \DateTime();
	}
}
