<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class CreateInvoiceLineItemResponse
{
	
    public string $contentType;
    
    /**
     * Created
     * 
     * @var ?\orb\orb\Models\Shared\InvoiceLineItem $invoiceLineItem
     */
	
    public ?\orb\orb\Models\Shared\InvoiceLineItem $invoiceLineItem = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->invoiceLineItem = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
