<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * This is used for creating charges or invoices in an external system via Orb. When not in test mode:
 * 
 * - the connection must first be configured in the Orb webapp. 
 * - if the provider is an invoicing provider (`stripe_invoice`, `quickbooks`, `bill.com`), any product mappings must first be configured with the Orb team.
 */
enum CreateCustomerRequestBodyPaymentProvider: string
{
    case Quickbooks = 'quickbooks';
    case BillCom = 'bill.com';
    case StripeCharge = 'stripe_charge';
    case StripeInvoice = 'stripe_invoice';
    case Null = 'null';
}
