<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * CreateSubscriptionApplicationJSONPriceOverrides7 - Tiered BPS price override
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class CreateSubscriptionApplicationJSONPriceOverrides7
{
    /**
     * The subscription's override discount for this price.
     * 
     * @var ?\orb\orb\Models\Shared\CreateDiscount $discount
     */
	#[\JMS\Serializer\Annotation\SerializedName('discount')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Shared\CreateDiscount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\orb\orb\Models\Shared\CreateDiscount $discount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The subscription's override minimum amount for this price.
     * 
     * @var ?string $minimumAmount
     */
	#[\JMS\Serializer\Annotation\SerializedName('minimum_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $minimumAmount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('model_type')]
    #[\JMS\Serializer\Annotation\Type('enum<orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides7ModelType>')]
    public CreateSubscriptionApplicationJSONPriceOverrides7ModelType $modelType;
    
	#[\JMS\Serializer\Annotation\SerializedName('tiered_bps_config')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfig')]
    public CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfig $tieredBpsConfig;
    
	public function __construct()
	{
		$this->discount = null;
		$this->id = "";
		$this->minimumAmount = null;
		$this->modelType = \orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides7ModelType::TIERED_BPS;
		$this->tieredBpsConfig = new \orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfig();
	}
}
