<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


enum CreateSubscriptionApplicationJSONPriceOverrides4ModelType: string
{
    case PACKAGE = 'package';
}
