<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * CreateLedgerEntryRequestBodyMetadata - User-specified key/value pairs for the ledger entry resource.
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class CreateLedgerEntryRequestBodyMetadata
{
	public function __construct()
	{
	}
}
