<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * CreateSubscriptionApplicationJSONMetadata - User-specified key value pairs, often useful for referencing internal resources or IDs. Returned as-is in the subscription resource.
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class CreateSubscriptionApplicationJSONMetadata
{
	public function __construct()
	{
	}
}
