<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * CreateSubscriptionApplicationJSONPriceOverrides3 - Bulk price override
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class CreateSubscriptionApplicationJSONPriceOverrides3
{
	#[\JMS\Serializer\Annotation\SerializedName('bulk_config')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides3BulkConfig')]
    public CreateSubscriptionApplicationJSONPriceOverrides3BulkConfig $bulkConfig;
    
    /**
     * The subscription's override discount for this price.
     * 
     * @var ?\orb\orb\Models\Shared\CreateDiscount $discount
     */
	#[\JMS\Serializer\Annotation\SerializedName('discount')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Shared\CreateDiscount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\orb\orb\Models\Shared\CreateDiscount $discount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The subscription's override minimum amount for this price.
     * 
     * @var ?string $minimumAmount
     */
	#[\JMS\Serializer\Annotation\SerializedName('minimum_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $minimumAmount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('model_type')]
    #[\JMS\Serializer\Annotation\Type('enum<orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides3ModelType>')]
    public CreateSubscriptionApplicationJSONPriceOverrides3ModelType $modelType;
    
	public function __construct()
	{
		$this->bulkConfig = new \orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides3BulkConfig();
		$this->discount = null;
		$this->id = "";
		$this->minimumAmount = null;
		$this->modelType = \orb\orb\Models\Operations\CreateSubscriptionApplicationJSONPriceOverrides3ModelType::Bulk;
	}
}
