<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class DeprecateEventResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\orb\orb\Models\Operations\DeprecateEvent200ApplicationJSON $deprecateEvent200ApplicationJSONObject
     */
	
    public ?DeprecateEvent200ApplicationJSON $deprecateEvent200ApplicationJSONObject = null;
    
    /**
     * Bad Request
     * 
     * @var ?\orb\orb\Models\Operations\DeprecateEvent400ApplicationJSON $deprecateEvent400ApplicationJSONObject
     */
	
    public ?DeprecateEvent400ApplicationJSON $deprecateEvent400ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deprecateEvent200ApplicationJSONObject = null;
		$this->deprecateEvent400ApplicationJSONObject = null;
	}
}
