<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * FetchSubscriptionUsage200ApplicationJSON - OK
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class FetchSubscriptionUsage200ApplicationJSON
{
    /**
     * $data
     * 
     * @var ?array<\orb\orb\Models\Operations\FetchSubscriptionUsage200ApplicationJSONData> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Operations\FetchSubscriptionUsage200ApplicationJSONData>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
	public function __construct()
	{
		$this->data = null;
	}
}
