<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class FetchCustomerCostsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\orb\orb\Models\Operations\FetchCustomerCosts200ApplicationJSON $fetchCustomerCosts200ApplicationJSONObject
     */
	
    public ?FetchCustomerCosts200ApplicationJSON $fetchCustomerCosts200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->fetchCustomerCosts200ApplicationJSONObject = null;
	}
}
