<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class FetchCouponRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=coupon_id')]
    public string $couponId;
    
	public function __construct()
	{
		$this->couponId = "";
	}
}
