<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * FetchCustomerCreditsExternalId200ApplicationJSON - OK
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class FetchCustomerCreditsExternalId200ApplicationJSON
{
    /**
     * $data
     * 
     * @var array<\orb\orb\Models\Operations\FetchCustomerCreditsExternalId200ApplicationJSONData> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Operations\FetchCustomerCreditsExternalId200ApplicationJSONData>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('pagination_metadata')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Operations\FetchCustomerCreditsExternalId200ApplicationJSONPaginationMetadata')]
    public FetchCustomerCreditsExternalId200ApplicationJSONPaginationMetadata $paginationMetadata;
    
	public function __construct()
	{
		$this->data = [];
		$this->paginationMetadata = new \orb\orb\Models\Operations\FetchCustomerCreditsExternalId200ApplicationJSONPaginationMetadata();
	}
}
