<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class FetchCustomerCreditsExternalIdRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_customer_id')]
    public string $externalCustomerId;
    
	public function __construct()
	{
		$this->externalCustomerId = "";
	}
}
