<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * GetCustomersCustomerIdBalanceTransactions200ApplicationJSON - OK
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class GetCustomersCustomerIdBalanceTransactions200ApplicationJSON
{
    /**
     * $data
     * 
     * @var ?array<\orb\orb\Models\Shared\CustomerBalanceTransaction> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\CustomerBalanceTransaction>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
    /**
     * $paginationMetadata
     * 
     * @var ?array<string, mixed> $paginationMetadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('pagination_metadata')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $paginationMetadata = null;
    
	public function __construct()
	{
		$this->data = null;
		$this->paginationMetadata = null;
	}
}
