<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * GetCustomersCustomerIdCreditsLedger200ApplicationJSON - OK
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class GetCustomersCustomerIdCreditsLedger200ApplicationJSON
{
    /**
     * $data
     * 
     * @var array<\orb\orb\Models\Shared\CreditLedgerEntry> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\CreditLedgerEntry>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('pagination_metadata')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Operations\GetCustomersCustomerIdCreditsLedger200ApplicationJSONPaginationMetadata')]
    public GetCustomersCustomerIdCreditsLedger200ApplicationJSONPaginationMetadata $paginationMetadata;
    
	public function __construct()
	{
		$this->data = [];
		$this->paginationMetadata = new \orb\orb\Models\Operations\GetCustomersCustomerIdCreditsLedger200ApplicationJSONPaginationMetadata();
	}
}
