<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/** Filters to a single status of ledger entry */
enum GetCustomersCustomerIdCreditsLedgerEntryStatusEnum: string
{
    case COMMITTED = 'committed';
    case PENDING = 'pending';
}
