<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;

use \Orb\Orb\Utils\SpeakeasyMetadata;
class GetInvoicesUpcomingRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=subscription_id')]
    public string $subscriptionId;
    
	public function __construct()
	{
		$this->subscriptionId = "";
	}
}
