<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;

use \Orb\Orb\Utils\SpeakeasyMetadata;
class GetInvoiceInvoiceIdRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=invoice_id')]
    public string $invoiceId;
    
	public function __construct()
	{
		$this->invoiceId = "";
	}
}
