<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;

use \Orb\Orb\Utils\SpeakeasyMetadata;
class GetPlansExternalPlanIdRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\Orb\Orb\Models\Shared\Plan $plan = null;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_plan_id')]
    public string $externalPlanId;
    
	public function __construct()
	{
		$this->plan = null;
		$this->externalPlanId = "";
	}
}
