<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;

use \Orb\Orb\Utils\SpeakeasyMetadata;
class GetPlansPlanIdRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=plan_id')]
    public string $planId;
    
	public function __construct()
	{
		$this->planId = "";
	}
}
