<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


/** This determines the windowing of usage reporting. */
enum GetSubscriptionsSubscriptionIdUsageGranularityEnum: string
{
    case DAY = 'day';
}
