<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class IngestRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?IngestRequestBody $requestBody = null;
    
    /**
     * If this ingestion request is part of a backfill, this parameter ties the ingested events to the backfill
     * 
     * @var ?string $backfillId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=backfill_id')]
    public ?string $backfillId = null;
    
    /**
     * Flag to enable additional debug information in the endpoint response
     * 
     * @var ?\orb\orb\Models\Operations\IngestDebug $debug
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=debug')]
    public ?IngestDebug $debug = null;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->backfillId = null;
		$this->debug = null;
	}
}
