<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class ListPlansRequestBody
{
    /**
     * $data
     * 
     * @var ?array<\orb\orb\Models\Shared\Plan> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\Plan>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
    /**
     * $paginationMetadata
     * 
     * @var ?array<string, mixed> $paginationMetadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('pagination_metadata')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $paginationMetadata = null;
    
	public function __construct()
	{
		$this->data = null;
		$this->paginationMetadata = null;
	}
}
