<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class ListSubscriptionsRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=customer_id')]
    public ?string $customerId = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_customer_id')]
    public ?string $externalCustomerId = null;
    
	public function __construct()
	{
		$this->customerId = null;
		$this->externalCustomerId = null;
	}
}
