<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class ListCouponsRequest
{
    /**
     * Filter to coupons matching this redemption code.
     * 
     * @var ?string $redemptionCode
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=redemption_code')]
    public ?string $redemptionCode = null;
    
    /**
     * Show archived coupons as well (by default, this endpoint only returns active coupons).
     * 
     * @var ?bool $showArchived
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=show_archived')]
    public ?bool $showArchived = null;
    
	public function __construct()
	{
		$this->redemptionCode = null;
		$this->showArchived = null;
	}
}
