<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


class PatchExternalCustomersCustomerIdUsageResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Orb\Orb\Models\Operations\PatchExternalCustomersCustomerIdUsage200ApplicationJSON $patchExternalCustomersCustomerIdUsage200ApplicationJSONObject
     */
	
    public ?PatchExternalCustomersCustomerIdUsage200ApplicationJSON $patchExternalCustomersCustomerIdUsage200ApplicationJSONObject = null;
    
    /**
     * Bad Request
     * 
     * @var ?\Orb\Orb\Models\Operations\PatchExternalCustomersCustomerIdUsage400ApplicationJSON $patchExternalCustomersCustomerIdUsage400ApplicationJSONObject
     */
	
    public ?PatchExternalCustomersCustomerIdUsage400ApplicationJSON $patchExternalCustomersCustomerIdUsage400ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->patchExternalCustomersCustomerIdUsage200ApplicationJSONObject = null;
		$this->patchExternalCustomersCustomerIdUsage400ApplicationJSONObject = null;
	}
}
