<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


class PatchExternalCustomersCustomerIdUsageRequestBody
{
    /**
     * $events
     * 
     * @var array<\Orb\Orb\Models\Operations\PatchExternalCustomersCustomerIdUsageRequestBodyEvents> $events
     */
	#[\JMS\Serializer\Annotation\SerializedName('events')]
    #[\JMS\Serializer\Annotation\Type('array<Orb\Orb\Models\Operations\PatchExternalCustomersCustomerIdUsageRequestBodyEvents>')]
    public array $events;
    
	public function __construct()
	{
		$this->events = [];
	}
}
