<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


enum PostSubscriptionsRequestBodyPriceOverrides3ModelTypeEnum: string
{
    case BULK = 'bulk';
}
