<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class PostSubscriptionsSubscriptionIdCancelRequest
{
    /**
     * Determines the timing of subscription cancellation
     * 
     * @var \orb\orb\Models\Operations\PostSubscriptionsSubscriptionIdCancelCancelOption $cancelOption
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cancel_option')]
    public PostSubscriptionsSubscriptionIdCancelCancelOption $cancelOption;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscription_id')]
    public string $subscriptionId;
    
	public function __construct()
	{
		$this->cancelOption = \orb\orb\Models\Operations\PostSubscriptionsSubscriptionIdCancelCancelOption::END_OF_SUBSCRIPTION_TERM;
		$this->subscriptionId = "";
	}
}
