<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class PostIngestResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\orb\orb\Models\Operations\PostIngest200ApplicationJSON $postIngest200ApplicationJSONObject
     */
	
    public ?PostIngest200ApplicationJSON $postIngest200ApplicationJSONObject = null;
    
    /**
     * Bad Request
     * 
     * @var ?\orb\orb\Models\Operations\PostIngest400ApplicationJSON $postIngest400ApplicationJSONObject
     */
	
    public ?PostIngest400ApplicationJSON $postIngest400ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postIngest200ApplicationJSONObject = null;
		$this->postIngest400ApplicationJSONObject = null;
	}
}
