<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class PostIngestRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PostIngestRequestBody $requestBody = null;
    
    /**
     * Flag to enable additional debug information in the endpoint response
     * 
     * @var ?\orb\orb\Models\Operations\PostIngestDebugEnum $debug
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=debug')]
    public ?PostIngestDebugEnum $debug = null;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->debug = null;
	}
}
