<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


class PostSubscriptionsRequestBodyPriceOverrides4PackageConfig
{
	#[\JMS\Serializer\Annotation\SerializedName('package_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $packageAmount;
    
	#[\JMS\Serializer\Annotation\SerializedName('package_size')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $packageSize;
    
	public function __construct()
	{
		$this->packageAmount = "";
		$this->packageSize = 0;
	}
}
