<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


enum PostSubscriptionsRequestBodyPriceOverrides1ModelType: string
{
    case TIERED = 'tiered';
}
