<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/** Optionally provide the name of the external marketplace that the subscription is attached to. */
enum PostSubscriptionsRequestBodyExternalMarketplace: string
{
    case GOOGLE = 'google';
    case AWS = 'aws';
    case AZURE = 'azure';
}
