<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


enum PostCustomersCustomerIdCreditsLedgerEntryRequestBodyEntryTypeEnum: string
{
    case INCREMENT = 'increment';
    case DECREMENT = 'decrement';
    case EXPIRATION_CHANGE = 'expiration_change';
}
