<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


/**
 * PostSubscriptionsRequestBodyPriceOverrides4 - Package price override
 * 
 * @package Orb\Orb\Models\Operations
 * @access public
 */
class PostSubscriptionsRequestBodyPriceOverrides4
{
    /**
     * $discount
     * 
     * @var ?array<string, mixed> $discount
     */
	#[\JMS\Serializer\Annotation\SerializedName('discount')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $discount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The subscription's override minimum amount for this price.
     * 
     * @var ?string $minimumAmount
     */
	#[\JMS\Serializer\Annotation\SerializedName('minimum_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $minimumAmount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('model_type')]
    #[\JMS\Serializer\Annotation\Type('enum<Orb\Orb\Models\Operations\PostSubscriptionsRequestBodyPriceOverrides4ModelTypeEnum>')]
    public PostSubscriptionsRequestBodyPriceOverrides4ModelTypeEnum $modelType;
    
	#[\JMS\Serializer\Annotation\SerializedName('package_config')]
    #[\JMS\Serializer\Annotation\Type('Orb\Orb\Models\Operations\PostSubscriptionsRequestBodyPriceOverrides4PackageConfig')]
    public PostSubscriptionsRequestBodyPriceOverrides4PackageConfig $packageConfig;
    
	public function __construct()
	{
		$this->discount = null;
		$this->id = "";
		$this->minimumAmount = null;
		$this->modelType = \Orb\Orb\Models\Operations\PostSubscriptionsRequestBodyPriceOverrides4ModelTypeEnum::PACKAGE;
		$this->packageConfig = new \Orb\Orb\Models\Operations\PostSubscriptionsRequestBodyPriceOverrides4PackageConfig();
	}
}
