<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/** Flag to enable additional debug information in the endpoint response */
enum PostIngestDebugEnum: string
{
    case TRUE = 'true';
    case FALSE = 'false';
}
