<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


/**
 * PostIngest200ApplicationJSON - OK
 * 
 * @package Orb\Orb\Models\Operations
 * @access public
 */
class PostIngest200ApplicationJSON
{
    /**
     * Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
     * 
     * @var ?\Orb\Orb\Models\Operations\PostIngest200ApplicationJSONDebug $debug
     */
	#[\JMS\Serializer\Annotation\SerializedName('debug')]
    #[\JMS\Serializer\Annotation\Type('Orb\Orb\Models\Operations\PostIngest200ApplicationJSONDebug')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PostIngest200ApplicationJSONDebug $debug = null;
    
    /**
     * Contains all failing validation events. In the case of a 200, this array will always be empty. This field will always be present.
     * 
     * @var array<\Orb\Orb\Models\Operations\PostIngest200ApplicationJSONValidationFailed> $validationFailed
     */
	#[\JMS\Serializer\Annotation\SerializedName('validation_failed')]
    #[\JMS\Serializer\Annotation\Type('array<Orb\Orb\Models\Operations\PostIngest200ApplicationJSONValidationFailed>')]
    public array $validationFailed;
    
	public function __construct()
	{
		$this->debug = null;
		$this->validationFailed = [];
	}
}
