<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;

use \orb\orb\Utils\SpeakeasyMetadata;
class PostInvoicesInvoiceIdVoidRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=invoice_id')]
    public string $invoiceId;
    
	public function __construct()
	{
		$this->invoiceId = "";
	}
}
