<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


/**
 * This is used for creating charges or invoices in an external system via Orb. When not in test mode:
 * 
 * - the connection must first be configured in the Orb webapp. 
 * - if the provider is an invoicing provider (`stripe_invoice`, `quickbooks`, `bill.com`), any product mappings must first be configured with the Orb team.
 */
enum PutCustomersCustomerIdRequestBodyPaymentProviderEnum: string
{
    case STRIPE_INVOICE = 'stripe_invoice';
    case QUICKBOOKS = 'quickbooks';
    case BILL_COM = 'bill.com';
    case STRIPE_CHARGE = 'stripe_charge';
    case NULL = 'null';
}
