<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * PutDeprecateEventsEventId200ApplicationJSON - OK
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class PutDeprecateEventsEventId200ApplicationJSON
{
    /**
     * event_id of the deprecated event, if successfully updated
     * 
     * @var ?string $deprecated
     */
	#[\JMS\Serializer\Annotation\SerializedName('deprecated')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $deprecated = null;
    
	public function __construct()
	{
		$this->deprecated = null;
	}
}
