<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


class PutDeprecateEventsEventIdResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Orb\Orb\Models\Operations\PutDeprecateEventsEventId200ApplicationJSON $putDeprecateEventsEventId200ApplicationJSONObject
     */
	
    public ?PutDeprecateEventsEventId200ApplicationJSON $putDeprecateEventsEventId200ApplicationJSONObject = null;
    
    /**
     * Bad Request
     * 
     * @var ?\Orb\Orb\Models\Operations\PutDeprecateEventsEventId400ApplicationJSON $putDeprecateEventsEventId400ApplicationJSONObject
     */
	
    public ?PutDeprecateEventsEventId400ApplicationJSON $putDeprecateEventsEventId400ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->putDeprecateEventsEventId200ApplicationJSONObject = null;
		$this->putDeprecateEventsEventId400ApplicationJSONObject = null;
	}
}
