<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Operations;


/**
 * PutEventsEventId200ApplicationJSON - OK
 * 
 * @package Orb\Orb\Models\Operations
 * @access public
 */
class PutEventsEventId200ApplicationJSON
{
    /**
     * event_id of the amended event, if successfully ingested
     * 
     * @var ?string $amended
     */
	#[\JMS\Serializer\Annotation\SerializedName('amended')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $amended = null;
    
	public function __construct()
	{
		$this->amended = null;
	}
}
