<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class PutEventsEventIdResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\orb\orb\Models\Operations\PutEventsEventId200ApplicationJSON $putEventsEventId200ApplicationJSONObject
     */
	
    public ?PutEventsEventId200ApplicationJSON $putEventsEventId200ApplicationJSONObject = null;
    
    /**
     * Bad Request
     * 
     * @var ?\orb\orb\Models\Operations\PutEventsEventId400ApplicationJSON $putEventsEventId400ApplicationJSONObject
     */
	
    public ?PutEventsEventId400ApplicationJSON $putEventsEventId400ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->putEventsEventId200ApplicationJSONObject = null;
		$this->putEventsEventId400ApplicationJSONObject = null;
	}
}
