<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


enum SchedulePlanChangeRequestBodyPriceOverrides6ModelType: string
{
    case BULK_BPS = 'bulk_bps';
}
