<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/**
 * SchedulePlanChangeRequestBodyPriceOverrides3 - Bulk price override
 * 
 * @package orb\orb\Models\Operations
 * @access public
 */
class SchedulePlanChangeRequestBodyPriceOverrides3
{
	#[\JMS\Serializer\Annotation\SerializedName('bulk_config')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Operations\SchedulePlanChangeRequestBodyPriceOverrides3BulkConfig')]
    public SchedulePlanChangeRequestBodyPriceOverrides3BulkConfig $bulkConfig;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The subscription's override minimum amount for this price.
     * 
     * @var ?string $minimumAmount
     */
	#[\JMS\Serializer\Annotation\SerializedName('minimum_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $minimumAmount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('model_type')]
    #[\JMS\Serializer\Annotation\Type('enum<orb\orb\Models\Operations\SchedulePlanChangeRequestBodyPriceOverrides3ModelType>')]
    public SchedulePlanChangeRequestBodyPriceOverrides3ModelType $modelType;
    
	public function __construct()
	{
		$this->bulkConfig = new \orb\orb\Models\Operations\SchedulePlanChangeRequestBodyPriceOverrides3BulkConfig();
		$this->id = "";
		$this->minimumAmount = null;
		$this->modelType = \orb\orb\Models\Operations\SchedulePlanChangeRequestBodyPriceOverrides3ModelType::BULK;
	}
}
