<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class SchedulePlanChangeRequestBodyPriceOverrides1TieredConfigTiers
{
	#[\JMS\Serializer\Annotation\SerializedName('first_unit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $firstUnit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('last_unit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lastUnit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unitAmount = null;
    
	public function __construct()
	{
		$this->firstUnit = null;
		$this->lastUnit = null;
		$this->unitAmount = null;
	}
}
