<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


/** Determines the timing of the plan change */
enum SchedulePlanChangeRequestBodyChangeOption: string
{
    case RequestedDate = 'requested_date';
    case EndOfSubscriptionTerm = 'end_of_subscription_term';
    case Immediate = 'immediate';
}
