<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Operations;


class SchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfig
{
    /**
     * $tiers
     * 
     * @var ?array<\orb\orb\Models\Operations\SchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfigTiers> $tiers
     */
	#[\JMS\Serializer\Annotation\SerializedName('tiers')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Operations\SchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfigTiers>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $tiers = null;
    
	public function __construct()
	{
		$this->tiers = null;
	}
}
