<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/** The status of the backfill. */
enum BackfillStatus: string
{
    case PENDING = 'pending';
    case REFLECTED = 'reflected';
    case PENDING_REVERT = 'pending_revert';
    case REVERTED = 'reverted';
}
