<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/** The status of the backfill. */
enum BackfillStatus: string
{
    case Pending = 'pending';
    case Reflected = 'reflected';
    case PendingRevert = 'pending_revert';
    case Reverted = 'reverted';
}
