<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


enum CreateDiscountDiscountType: string
{
    case PERCENTAGE = 'percentage';
    case USAGE = 'usage';
    case AMOUNT = 'amount';
}
