<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


class CreditNoteLineItem
{
    /**
     * The amount of the line item, including any line item minimums and discounts
     * 
     * @var string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
	#[\JMS\Serializer\Annotation\SerializedName('discounts')]
    #[\JMS\Serializer\Annotation\Type('orb\orb\Models\Shared\Discount')]
    public Discount $discounts;
    
    /**
     * The Orb id of this resource
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The name of the corresponding invoice line item
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * An optional quantity credited.
     * 
     * @var float $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $quantity;
    
    /**
     * Any sub line items that may be credited.
     * 
     * @var array<\orb\orb\Models\Shared\CreditNoteLineItemSubLineItems> $subLineItems
     */
	#[\JMS\Serializer\Annotation\SerializedName('sub_line_items')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\CreditNoteLineItemSubLineItems>')]
    public array $subLineItems;
    
    /**
     * The amount of the line item, excluding any line item minimums and discounts
     * 
     * @var string $subtotal
     */
	#[\JMS\Serializer\Annotation\SerializedName('subtotal')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $subtotal;
    
    /**
     * Any tax amounts applied onto the line item.
     * 
     * @var array<\orb\orb\Models\Shared\CreditNoteLineItemTaxAmounts> $taxAmounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax_amounts')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\CreditNoteLineItemTaxAmounts>')]
    public array $taxAmounts;
    
	public function __construct()
	{
		$this->amount = "";
		$this->discounts = new \orb\orb\Models\Shared\Discount();
		$this->id = "";
		$this->name = "";
		$this->quantity = 0;
		$this->subLineItems = [];
		$this->subtotal = "";
		$this->taxAmounts = [];
	}
}
