<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


enum CreditLedgerEntryEntryTypeEnum: string
{
    case INCREMENT = 'increment';
    case DECREMENT = 'decrement';
    case EXPIRATION_CHANGE = 'expiration_change';
    case CREDIT_BLOCK_EXPIRY = 'credit_block_expiry';
}
