<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


class CreditNoteLineItemTaxAmounts
{
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
	#[\JMS\Serializer\Annotation\SerializedName('tax_rate_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $taxRateDescription;
    
	#[\JMS\Serializer\Annotation\SerializedName('tax_rate_percentage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $taxRatePercentage;
    
	public function __construct()
	{
		$this->amount = "";
		$this->taxRateDescription = "";
		$this->taxRatePercentage = "";
	}
}
