<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/** Describes the reason that this transaction took place. */
enum CustomerBalanceTransactionAction: string
{
    case AppliedToInvoice = 'applied_to_invoice';
    case ProratedRefund = 'prorated_refund';
    case ManualAdjustment = 'manual_adjustment';
}
