<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


/** The external payments or invoicing solution connected to this customer. */
enum CustomerPaymentProviderEnum: string
{
    case STRIPE = 'stripe';
    case QUICKBOOKS = 'quickbooks';
    case BILL_COM = 'bill.com';
    case STRIPE_CHARGE = 'stripe_charge';
    case STRIPE_INVOICE = 'stripe_invoice';
    case NULL = 'null';
}
