<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/** The external payments or invoicing solution connected to this customer. */
enum CustomerPaymentProvider: string
{
    case STRIPE = 'stripe';
    case QUICKBOOKS = 'quickbooks';
    case BILL_COM = 'bill.com';
    case STRIPE_CHARGE = 'stripe_charge';
    case STRIPE_INVOICE = 'stripe_invoice';
    case LESS_THAN_NIL_GREATER_THAN = '<nil>';
}
