<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/** The external payments or invoicing solution connected to this customer. */
enum CustomerPaymentProvider: string
{
    case Stripe = 'stripe';
    case Quickbooks = 'quickbooks';
    case BillCom = 'bill.com';
    case StripeCharge = 'stripe_charge';
    case StripeInvoice = 'stripe_invoice';
    case LessThanNilGreaterThan = '<nil>';
}
