<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


/** Describes the reason that this transaction took place. */
enum CustomerBalanceTransactionActionEnum: string
{
    case APPLIED_TO_INVOICE = 'applied_to_invoice';
    case PRORATED_REFUND = 'prorated_refund';
    case MANUAL_ADJUSTMENT = 'manual_adjustment';
}
