<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/**
 * CustomerMetadata - User specified key-value pairs. If there is no metadata for the customer, this defaults to an empty dictionary.
 * 
 * @package orb\orb\Models\Shared
 * @access public
 */
class CustomerMetadata
{
	public function __construct()
	{
	}
}
