<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


/**
 * CustomerBalanceTransaction - A single change to the customer balance. All amounts are in the customer's currency.
 * 
 * @package Orb\Orb\Models\Shared
 * @access public
 */
class CustomerBalanceTransaction
{
    /**
     * Describes the reason that this transaction took place.
     * 
     * @var \Orb\Orb\Models\Shared\CustomerBalanceTransactionActionEnum $action
     */
	#[\JMS\Serializer\Annotation\SerializedName('action')]
    #[\JMS\Serializer\Annotation\Type('enum<Orb\Orb\Models\Shared\CustomerBalanceTransactionActionEnum>')]
    public CustomerBalanceTransactionActionEnum $action;
    
    /**
     * The value of the amount changed in the transaction.
     * 
     * @var string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
    /**
     * The creation time of this transaction.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * An optional description provided for manual customer balance adjustments.
     * 
     * @var string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
    /**
     * The new value of the customer's balance prior to the transaction, in the customer's currency.
     * 
     * @var string $endingBalance
     */
	#[\JMS\Serializer\Annotation\SerializedName('ending_balance')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $endingBalance;
    
    /**
     * A unique id for this transaction.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The Invoice associated with this transaction
     * 
     * @var \Orb\Orb\Models\Shared\CustomerBalanceTransactionInvoice $invoice
     */
	#[\JMS\Serializer\Annotation\SerializedName('invoice')]
    #[\JMS\Serializer\Annotation\Type('Orb\Orb\Models\Shared\CustomerBalanceTransactionInvoice')]
    public CustomerBalanceTransactionInvoice $invoice;
    
    /**
     * The original value of the customer's balance prior to the transaction, in the customer's currency.
     * 
     * @var string $startingBalance
     */
	#[\JMS\Serializer\Annotation\SerializedName('starting_balance')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $startingBalance;
    
	public function __construct()
	{
		$this->action = \Orb\Orb\Models\Shared\CustomerBalanceTransactionActionEnum::APPLIED_TO_INVOICE;
		$this->amount = "";
		$this->createdAt = new \DateTime();
		$this->description = "";
		$this->endingBalance = "";
		$this->id = "";
		$this->invoice = new \Orb\Orb\Models\Shared\CustomerBalanceTransactionInvoice();
		$this->startingBalance = "";
	}
}
