<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


enum DiscountDiscountType: string
{
    case Percentage = 'percentage';
    case Trial = 'trial';
    case Usage = 'usage';
    case Amount = 'amount';
}
