<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


class Discount
{
    /**
     * Only available if discount_type is `amount`. 
     * 
     * @var ?string $amountDiscount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount_discount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $amountDiscount = null;
    
    /**
     * List of price_ids that this discount applies to. For plan/plan phase discounts, this can be a subset of prices.
     * 
     * @var ?array<string> $appliesToPriceIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('applies_to_price_ids')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $appliesToPriceIds = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('discount_type')]
    #[\JMS\Serializer\Annotation\Type('enum<orb\orb\Models\Shared\DiscountDiscountType>')]
    public DiscountDiscountType $discountType;
    
    /**
     * Only available if discount_type is `percentage`.This is a number between 0 and 1.
     * 
     * @var ?float $percentageDiscount
     */
	#[\JMS\Serializer\Annotation\SerializedName('percentage_discount')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $percentageDiscount = null;
    
    /**
     * Only available if discount_type is `trial`
     * 
     * @var ?string $trialAmountDiscount
     */
	#[\JMS\Serializer\Annotation\SerializedName('trial_amount_discount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $trialAmountDiscount = null;
    
    /**
     * Only available if discount_type is `usage`. Number of usage units that this discount is for
     * 
     * @var ?float $usageDiscount
     */
	#[\JMS\Serializer\Annotation\SerializedName('usage_discount')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $usageDiscount = null;
    
	public function __construct()
	{
		$this->amountDiscount = null;
		$this->appliesToPriceIds = null;
		$this->discountType = \orb\orb\Models\Shared\DiscountDiscountType::Percentage;
		$this->percentageDiscount = null;
		$this->trialAmountDiscount = null;
		$this->usageDiscount = null;
	}
}
