<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


class InvoiceLineItemsTaxAmounts
{
    /**
     * The amount of additional tax incurred by this tax rate.
     * 
     * @var string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
    /**
     * The human-readable description of the applied tax rate.
     * 
     * @var string $taxRateDescription
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax_rate_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $taxRateDescription;
    
    /**
     * The tax rate percentage, out of 100.
     * 
     * @var string $taxRatePercentage
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax_rate_percentage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $taxRatePercentage;
    
	public function __construct()
	{
		$this->amount = "";
		$this->taxRateDescription = "";
		$this->taxRatePercentage = "";
	}
}
