<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


class MinimumAmount
{
    /**
     * List of price_ids that this minimum amount applies to. For plan/plan phase minimums, this can be a subset of prices.
     * 
     * @var array<string> $appliesToPriceIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('applies_to_price_ids')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $appliesToPriceIds;
    
    /**
     * Minimum amount applied
     * 
     * @var string $minimumAmount
     */
	#[\JMS\Serializer\Annotation\SerializedName('minimum_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $minimumAmount;
    
	public function __construct()
	{
		$this->appliesToPriceIds = [];
		$this->minimumAmount = "";
	}
}
