<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


class PlanTrialConfig
{
	#[\JMS\Serializer\Annotation\SerializedName('trial_period')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $trialPeriod = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('trial_period_unit')]
    #[\JMS\Serializer\Annotation\Type('enum<orb\orb\Models\Shared\PlanTrialConfigTrialPeriodUnitEnum>')]
    public PlanTrialConfigTrialPeriodUnitEnum $trialPeriodUnit;
    
	public function __construct()
	{
		$this->trialPeriod = null;
		$this->trialPeriodUnit = \orb\orb\Models\Shared\PlanTrialConfigTrialPeriodUnitEnum::DAYS;
	}
}
