<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


enum PriceModelType: string
{
    case UNIT = 'unit';
    case TIERED = 'tiered';
    case BULK = 'bulk';
    case PACKAGE = 'package';
    case BPS = 'bps';
    case TIERED_BPS = 'tiered_bps';
    case BULK_BPS = 'bulk_bps';
    case MATRIX = 'matrix';
}
