<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


/**
 * PriceBpsConfig - Provided when model_type is `bps`
 * 
 * @package Orb\Orb\Models\Shared
 * @access public
 */
class PriceBpsConfig
{
	#[\JMS\Serializer\Annotation\SerializedName('bps')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $bps = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('per_unit_maximum')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $perUnitMaximum = null;
    
	public function __construct()
	{
		$this->bps = null;
		$this->perUnitMaximum = null;
	}
}
