<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/**
 * PriceTieredBpsConfig - Provided when model_type is `tiered_bps`
 * 
 * @package orb\orb\Models\Shared
 * @access public
 */
class PriceTieredBpsConfig
{
    /**
     * $tiers
     * 
     * @var ?array<\orb\orb\Models\Shared\PriceTieredBpsConfigTiers> $tiers
     */
	#[\JMS\Serializer\Annotation\SerializedName('tiers')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\PriceTieredBpsConfigTiers>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $tiers = null;
    
	public function __construct()
	{
		$this->tiers = null;
	}
}
