<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/**
 * PriceMatrixConfig - Provided when model_type is `matrix`
 * 
 * @package orb\orb\Models\Shared
 * @access public
 */
class PriceMatrixConfig
{
	#[\JMS\Serializer\Annotation\SerializedName('default_unit_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $defaultUnitAmount = null;
    
    /**
     * $dimensions
     * 
     * @var ?array<string> $dimensions
     */
	#[\JMS\Serializer\Annotation\SerializedName('dimensions')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $dimensions = null;
    
    /**
     * $matrixValues
     * 
     * @var ?array<\orb\orb\Models\Shared\PriceMatrixConfigMatrixValues> $matrixValues
     */
	#[\JMS\Serializer\Annotation\SerializedName('matrix_values')]
    #[\JMS\Serializer\Annotation\Type('array<orb\orb\Models\Shared\PriceMatrixConfigMatrixValues>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $matrixValues = null;
    
	public function __construct()
	{
		$this->defaultUnitAmount = null;
		$this->dimensions = null;
		$this->matrixValues = null;
	}
}
