<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


/**
 * PriceBulkConfig - Provided when model_type is `bulk`
 * 
 * @package Orb\Orb\Models\Shared
 * @access public
 */
class PriceBulkConfig
{
    /**
     * $tiers
     * 
     * @var ?array<\Orb\Orb\Models\Shared\PriceBulkConfigTiers> $tiers
     */
	#[\JMS\Serializer\Annotation\SerializedName('tiers')]
    #[\JMS\Serializer\Annotation\Type('array<Orb\Orb\Models\Shared\PriceBulkConfigTiers>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $tiers = null;
    
	public function __construct()
	{
		$this->tiers = null;
	}
}
