<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


enum PriceCadence: string
{
    case Annual = 'annual';
    case Monthly = 'monthly';
    case Quarterly = 'quarterly';
}
