<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/**
 * PriceUnitConfig - Provided when model_type is `unit`
 * 
 * @package orb\orb\Models\Shared
 * @access public
 */
class PriceUnitConfig
{
	#[\JMS\Serializer\Annotation\SerializedName('unit_amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unitAmount = null;
    
	public function __construct()
	{
		$this->unitAmount = null;
	}
}
