<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/**
 * SubscriptionMetadata - User specified key-value pairs. If no metadata was specified at subscription creation time, this defaults to an empty dictionary.
 * 
 * @package orb\orb\Models\Shared
 * @access public
 */
class SubscriptionMetadata
{
	public function __construct()
	{
	}
}
