<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


enum SubscriptionStatus: string
{
    case Active = 'active';
    case Ended = 'ended';
    case Upcoming = 'upcoming';
}
