<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Orb\Orb\Models\Shared;


/**
 * UpcomingInvoiceLineItemsSubLineItemsMatrixConfig - Only available if `type` is `matrix`. Contains the values of the matrix that this `sub_line_item` represents.
 * 
 * @package Orb\Orb\Models\Shared
 * @access public
 */
class UpcomingInvoiceLineItemsSubLineItemsMatrixConfig
{
    /**
     * The ordered dimension values for this line item.
     * 
     * @var array<string> $dimensionValues
     */
	#[\JMS\Serializer\Annotation\SerializedName('dimension_values')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $dimensionValues;
    
	public function __construct()
	{
		$this->dimensionValues = [];
	}
}
