<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace orb\orb\Models\Shared;


/** An identifier for a sub line item that is specific to a pricing model. */
enum UpcomingInvoiceLineItemsSubLineItemsTypeEnum: string
{
    case MATRIX = 'matrix';
    case TIER = 'tier';
}
